// The "home screen" contains two actions:
// action 1 is "login screen" which navigate to the log in screen.  action 2 is "settings screen" which navigates you to the settings screen. Both of these actions can only be called from the home screen.

// The "login screen" contains three actions:
// actions 1 is "Go back" which navigates the user from the login screen to the home screen.
// actions 2 is "Login" which logs the user in.
// actions 3 is "Logout" which logs the user out.

// The "settings screen" contains three actions:
// actions 1 is "Go back" which navigates the user from the settings screen to the home screen.
// actions 2 is "Change username" which allows the user to change their account name. This actions can only be completed if the user is logged in.
// actions 3 is "Change password" which allows the user to change their account password. This actions can only be completed if the user is logged in.

//Generated by assistant: single dudes maybe friend
// The "screen1" contains two actions: action 1 is "screen2" which navigates the user to screen2. action 2 is "screen3" which navigates you to screen3. Both of these actions can only be called from screen1.

// The "screen2" contains three actions: action 1 is "login login" which logs the user in. action 2 is "login logout" which logs the user out. action 3 is "back" which navigates the user from screen2 to screen1.

// The "screen3" contains three actions: action 1 is "back" which navigates the user from screen3 to screen1. action 2 is "edit password" which allows the user to change their account password. This action can only be completed if the user is logged in. action 3 is "edit name" which allows the user to change their account name. This action can only be completed if the user is logged in.

const test = {
  screens: [
    {
      actions: ["screen2", "screen3", "screen5"],
      name: "screen1",
    },
    {
      actions: ["login", "logout", "back"],
      name: "screen2",
    },
    {
      actions: ["back", "edit name", "screen4"],
      name: "screen3",
    },
    {
      actions: ["back", "reset password", "edit account summary"],
      name: "screen4",
    },
    {
      actions: ["back", "screen6"],
      name: "screen5",
    },
    {
      actions: ["back", "like", "share", "follow"],
      name: "screen6",
    },
  ],
};

const testFunc = {
  description: "This function calls the given action from the current screen.",
  name: "execute_action",
  parameters: {
    properties: {
      action: {
        description: "The action being taken on the screen e.g. 'Go back', 'settings screen'",
        type: "string",
      },
      screen: {
        description: "The name of the current screen that the actions is called on e.g. 'login screen', 'home screen'",
        type: "string",
      },
    },
    required: ["action", "screen"],
    type: "object",
  },
};
